apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-kube-descheduler-operator

resources:
- https://github.com/redhat-cop/gitops-catalog/tree/main/kube-descheduler-operator/operator/overlays/stable
